[2024-11-20T18:40:21.551+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-20T18:40:21.570+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.transform_female_daily manual__2024-11-20T18:40:17.160117+00:00 [queued]>
[2024-11-20T18:40:21.579+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.transform_female_daily manual__2024-11-20T18:40:17.160117+00:00 [queued]>
[2024-11-20T18:40:21.580+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-11-20T18:40:21.599+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): transform_female_daily> on 2024-11-20 18:40:17.160117+00:00
[2024-11-20T18:40:21.611+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=312) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-20T18:40:21.613+0000] {standard_task_runner.py:72} INFO - Started process 314 to run task
[2024-11-20T18:40:21.613+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'transform_female_daily', 'manual__2024-11-20T18:40:17.160117+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpxmxvj3an']
[2024-11-20T18:40:21.615+0000] {standard_task_runner.py:105} INFO - Job 42: Subtask transform_female_daily
[2024-11-20T18:40:21.667+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_pipeline.transform_female_daily manual__2024-11-20T18:40:17.160117+00:00 [running]> on host a222285b4c57
[2024-11-20T18:40:22.143+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='transform_female_daily' AIRFLOW_CTX_EXECUTION_DATE='2024-11-20T18:40:17.160117+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-20T18:40:17.160117+00:00'
[2024-11-20T18:40:22.148+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-20T18:40:22.150+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-20T18:40:22.151+0000] {logging_mixin.py:190} INFO - Current task name:transform_female_daily state:running start_date:2024-11-20 18:40:21.572105+00:00
[2024-11-20T18:40:22.152+0000] {logging_mixin.py:190} INFO - Dag name:etl_pipeline and current dag run status:running
[2024-11-20T18:40:22.154+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-20T18:40:22.156+0000] {logging_mixin.py:190} INFO - File tidak ditemukan: FemaleDaily_Review Azarine Calm My Acne Sunscreen Moisturizer.csv
[2024-11-20T18:40:22.157+0000] {logging_mixin.py:190} INFO - File tidak ditemukan: FemaleDaily_Review Azarine Hydramax C Sunscreen Serum.csv
[2024-11-20T18:40:22.157+0000] {logging_mixin.py:190} INFO - File tidak ditemukan: FemaleDaily_Review Azarine Hydrashoote Sunscreen Gel.csv
[2024-11-20T18:40:22.158+0000] {logging_mixin.py:190} INFO - Tidak ada file yang berhasil digabungkan untuk grup: Azarine
[2024-11-20T18:40:22.159+0000] {logging_mixin.py:190} INFO - File tidak ditemukan: FemaleDaily_Review Skinaqua UV Moisture Gel.csv
[2024-11-20T18:40:22.160+0000] {logging_mixin.py:190} INFO - File tidak ditemukan: FemaleDaily_Review Skinaqua UV Moisture Milk.csv
[2024-11-20T18:40:22.161+0000] {logging_mixin.py:190} INFO - File tidak ditemukan: FemaleDaily_Review Skinaqua UV Whitening Milk.csv
[2024-11-20T18:40:22.162+0000] {logging_mixin.py:190} INFO - Tidak ada file yang berhasil digabungkan untuk grup: Skinaqua
[2024-11-20T18:40:22.175+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl/transform_female_daily.py", line 112, in transform_female_daily
    df = pd.read_csv(output_file)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/hasil data extract/FemaleDaily_Sunscreen Azarine.csv'
[2024-11-20T18:40:22.374+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-20T18:40:22.375+0000] {logging_mixin.py:190} INFO - Task start:2024-11-20 18:40:21.572105+00:00 end:2024-11-20 18:40:22.370832+00:00 duration:0.798727
[2024-11-20T18:40:22.376+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): transform_female_daily> dag:<DAG: etl_pipeline> dagrun:<DagRun etl_pipeline @ 2024-11-20 18:40:17.160117+00:00: manual__2024-11-20T18:40:17.160117+00:00, state:running, queued_at: 2024-11-20 18:40:17.246163+00:00. externally triggered: True>
[2024-11-20T18:40:22.378+0000] {logging_mixin.py:190} INFO - Failure caused by [Errno 2] No such file or directory: '/opt/***/data/hasil data extract/FemaleDaily_Sunscreen Azarine.csv'
[2024-11-20T18:40:22.379+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=etl_pipeline, task_id=transform_female_daily, run_id=manual__2024-11-20T18:40:17.160117+00:00, execution_date=20241120T184017, start_date=20241120T184021, end_date=20241120T184022
[2024-11-20T18:40:22.514+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-20T18:40:22.515+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 42 for task transform_female_daily ([Errno 2] No such file or directory: '/opt/airflow/data/hasil data extract/FemaleDaily_Sunscreen Azarine.csv'; 314)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl/transform_female_daily.py", line 112, in transform_female_daily
    df = pd.read_csv(output_file)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/hasil data extract/FemaleDaily_Sunscreen Azarine.csv'
[2024-11-20T18:40:22.593+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-20T18:40:22.637+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-20T18:40:22.643+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
