[2024-11-20T15:57:03.123+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-20T15:57:03.139+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.transform_female_daily manual__2024-11-20T15:47:36.829271+00:00 [queued]>
[2024-11-20T15:57:03.146+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.transform_female_daily manual__2024-11-20T15:47:36.829271+00:00 [queued]>
[2024-11-20T15:57:03.148+0000] {taskinstance.py:2866} INFO - Starting attempt 3 of 3
[2024-11-20T15:57:03.161+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): transform_female_daily> on 2024-11-20 15:47:36.829271+00:00
[2024-11-20T15:57:03.171+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=532) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-20T15:57:03.173+0000] {standard_task_runner.py:72} INFO - Started process 534 to run task
[2024-11-20T15:57:03.173+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'transform_female_daily', 'manual__2024-11-20T15:47:36.829271+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp921wvok7']
[2024-11-20T15:57:03.175+0000] {standard_task_runner.py:105} INFO - Job 25: Subtask transform_female_daily
[2024-11-20T15:57:03.221+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_pipeline.transform_female_daily manual__2024-11-20T15:47:36.829271+00:00 [running]> on host 5fadb8d48c54
[2024-11-20T15:57:03.651+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='transform_female_daily' AIRFLOW_CTX_EXECUTION_DATE='2024-11-20T15:47:36.829271+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-20T15:47:36.829271+00:00'
[2024-11-20T15:57:03.654+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-20T15:57:03.655+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-20T15:57:03.656+0000] {logging_mixin.py:190} INFO - Current task name:transform_female_daily state:running start_date:2024-11-20 15:57:03.140336+00:00
[2024-11-20T15:57:03.658+0000] {logging_mixin.py:190} INFO - Dag name:etl_pipeline and current dag run status:running
[2024-11-20T15:57:03.659+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-20T15:57:03.661+0000] {logging_mixin.py:190} INFO - File tidak ditemukan: FemaleDaily_Review Azarine Calm My Acne Sunscreen Moisturizer.csv
[2024-11-20T15:57:03.662+0000] {logging_mixin.py:190} INFO - File tidak ditemukan: FemaleDaily_Review Azarine Hydramax C Sunscreen Serum.csv
[2024-11-20T15:57:03.663+0000] {logging_mixin.py:190} INFO - File tidak ditemukan: FemaleDaily_Review Azarine Hydrashoote Sunscreen Gel.csv
[2024-11-20T15:57:03.664+0000] {logging_mixin.py:190} INFO - Tidak ada file yang berhasil digabungkan untuk grup: Azarine
[2024-11-20T15:57:03.665+0000] {logging_mixin.py:190} INFO - File tidak ditemukan: FemaleDaily_Review Skinaqua UV Moisture Gel.csv
[2024-11-20T15:57:03.667+0000] {logging_mixin.py:190} INFO - File tidak ditemukan: FemaleDaily_Review Skinaqua UV Moisture Milk.csv
[2024-11-20T15:57:03.668+0000] {logging_mixin.py:190} INFO - File tidak ditemukan: FemaleDaily_Review Skinaqua UV Whitening Milk.csv
[2024-11-20T15:57:03.669+0000] {logging_mixin.py:190} INFO - Tidak ada file yang berhasil digabungkan untuk grup: Skinaqua
[2024-11-20T15:57:03.674+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl/transform_female_daily.py", line 113, in transform_female_daily
    df = pd.read_csv(output_file)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/hasil data extract/FemaleDaily_Sunscreen Azarine.csv'
[2024-11-20T15:57:03.716+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-20T15:57:03.718+0000] {logging_mixin.py:190} INFO - Task start:2024-11-20 15:57:03.140336+00:00 end:2024-11-20 15:57:03.716506+00:00 duration:0.57617
[2024-11-20T15:57:03.719+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): transform_female_daily> dag:<DAG: etl_pipeline> dagrun:<DagRun etl_pipeline @ 2024-11-20 15:47:36.829271+00:00: manual__2024-11-20T15:47:36.829271+00:00, state:running, queued_at: 2024-11-20 15:56:59.012602+00:00. externally triggered: True>
[2024-11-20T15:57:03.720+0000] {logging_mixin.py:190} INFO - Failure caused by [Errno 2] No such file or directory: '/opt/***/data/hasil data extract/FemaleDaily_Sunscreen Azarine.csv'
[2024-11-20T15:57:03.721+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=etl_pipeline, task_id=transform_female_daily, run_id=manual__2024-11-20T15:47:36.829271+00:00, execution_date=20241120T154736, start_date=20241120T155703, end_date=20241120T155703
[2024-11-20T15:57:03.734+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-20T15:57:03.736+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 25 for task transform_female_daily ([Errno 2] No such file or directory: '/opt/airflow/data/hasil data extract/FemaleDaily_Sunscreen Azarine.csv'; 534)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl/transform_female_daily.py", line 113, in transform_female_daily
    df = pd.read_csv(output_file)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/hasil data extract/FemaleDaily_Sunscreen Azarine.csv'
[2024-11-20T15:57:03.794+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-20T15:57:03.813+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-20T15:57:03.821+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
